### ISSUE TITLE
Could you open source codes of firmware?

### ISSUE THREAD

**Issue by jhan153** [dcpedit/masonry#1]
Hi,
Thank you enough for giving via firmware, I want to build my own qmk firmware.
Especially I want to apply tap hold timing and my combo keys and custom processes, can you open it if you are using qmk?

**Comment by dcpedit** [comment]
Yes, it's already part of the main QMK source code.  I've updated my README with the link.  I'll include it here as well: https://github.com/qmk/qmk_firmware/tree/master/keyboards/dcpedit/masonry
